name: Set up Conda environment
inputs:
  environment-file:
    description: Conda environment file to use.
    default: environment.yml
  environment-name:
    description: Name to use for the Conda environment
    default: test
  extra-specs:
    description: Extra packages to install
    required: false
runs:
  using: composite
  steps:
    - name: Install ${{ inputs.environment-file }}
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ inputs.environment-file }}
        environment-name: ${{ inputs.environment-name }}
        create-args: ${{ inputs.extra-specs }}
        condarc-file: ci/condarc.yml
        cache-env: true
        cache-downloads: true
