name: Set up pandas
description: Runs all the setup steps required to have a built pandas ready to use
inputs:
  environment-file:
    default: environment.yml
  pyarrow-version:
      required: false
  is-pypy:
    default: false
  activate-environment:
    default: pandas-dev
  python-version:
    required: false
runs:
  using: composite
  steps:
    - name: Get Date
      id: get-date
      run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
      shell: bash

    - name: Cache Conda packages
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: conda-${{ runner.os }}-${{ runner.arch }}-${{ inputs.environment-file }}-${{ steps.get-date.outputs.today }}

    - name: Set Arrow version in ${{ inputs.environment-file }} to ${{ inputs.pyarrow-version }}
      run: |
        grep -q '\- pyarrow' ${{ inputs.environment-file }}
        sed -i "s/- pyarrow/- pyarrow=${{ inputs.pyarrow-version }}/" ${{ inputs.environment-file }}
        cat ${{ inputs.environment-file }}
      shell: bash
      if: ${{ inputs.pyarrow-version }}

    - name: Setup Mambaforge and install ${{ inputs.environment-file }} (Python ${{ inputs.python-version }})
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "0.21.2"
        use-mamba: true
        channels: conda-forge
        activate-environment: ${{ inputs.activate-environment }}
        channel-priority: strict
        environment-file: ${{ inputs.environment-file }}
        python-version: ${{ inputs.python-version }}
        use-only-tar-bz2: true
      if: ${{ inputs.is-pypy == 'false' }} # No pypy3.8 support

    - name: Pin setuptools (GH#44980)
      run: mamba install -n ${{ inputs.activate-environment }} 'setuptools<60.0.0'
      shell: bash
      if: ${{ inputs.is-pypy == 'false' }} # No pypy3.8 support

    - name: Setup PyPy
      uses: actions/setup-python@v2
      with:
        python-version: "pypy-3.8"
      if: ${{ inputs.is-pypy == 'true' }}

    - name: Setup PyPy dependencies
      # TODO: re-enable cov, its slowing the tests down though
      run: pip install Cython numpy python-dateutil pytz pytest>=6.0 pytest-xdist>=1.31.0 hypothesis>=5.5.3
      shell: bash
      if: ${{ inputs.is-pypy == 'true' }}
