kind: pipeline
type: docker
name: py37-arm64

platform:
  arch: arm64

steps:
- name: test
  image: python:3.7
  commands:
  - pip install --upgrade pip setuptools
  - pip install cython numpy python-dateutil pytz pytest pytest-xdist hypothesis
  - python setup.py build_ext -j 4
  - python -m pip install -e . --no-build-isolation --no-use-pep517
  - pytest -m "(not slow and not network and not clipboard and not arm_slow)" -n 2  --dist=loadfile -s --strict-markers --durations=30 --junitxml=test-data.xml pandas

trigger:
  branch:
  - master
  - feature/*
  event:
  - push
  - pull_request
