repos:
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.7
      hooks:
          - id: flake8
            language: python_venv
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.20
      hooks:
          - id: isort
            language: python_venv
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.7
