minimum_pre_commit_version: 2.15.0
exclude: ^LICENSES/|\.(html|csv|svg)$
# reserve "manual" for mypy and pyright
default_stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
ci:
    autofix_prs: false
repos:
-   repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        types_or: [python, rst, markdown]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: \.txt$
        stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
    -   id: trailing-whitespace
        stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
-   repo: https://github.com/cpplint/cpplint
    rev: 1.6.0
    hooks:
    -   id: cpplint
        # We don't lint all C files because we don't want to lint any that are built
        # from Cython files nor do we want to lint C files that we didn't modify for
        # this particular codebase (e.g. src/headers, src/klib). However,
        # we can lint all header files since they aren't "generated" like C files are.
        exclude: ^pandas/_libs/src/(klib|headers)/
        args: [--quiet, '--extensions=c,h', '--headers=h', --recursive, '--filter=-readability/casting,-runtime/int,-build/include_subdir']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: &flake8_dependencies
        - flake8==4.0.1
        - flake8-comprehensions==3.7.0
        - flake8-bugbear==21.3.2
        - pandas-dev-flaker==0.5.0