repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
        exclude: ^pandas/io/sql_scratch.py$|^vendor/$
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        language: python_venv
        additional_dependencies: [flake8-comprehensions]
        exclude: ^pandas/io/sql_scratch.py$|^vendor/$
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort
        language: python_venv
        exclude: ^pandas/__init__\.py$|^pandas/core/api\.py$
