sudo: false
language: python
# Default Python version is usually 2.7
python: 3.5

# To turn off cached cython files and compiler cache
# set NOCACHE-true
# To delete caches go to https://travis-ci.org/OWNER/REPOSITORY/caches or run
# travis cache --delete inside the project directory from the travis command line client
# The cache directories will be deleted if anything in ci/ changes in a commit
cache:
 ccache: true
 directories:
  - $HOME/.cache # cython cache
  - $HOME/.ccache # compiler cache

git:
    # for cloning
    depth: 1500

matrix:
    fast_finish: true
    exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5

    include:
    - dist: trusty
      env:
        - JOB="3.7" ENV_FILE="ci/deps/travis-37.yaml" TEST_ARGS="--skip-slow --skip-network"

    - dist: trusty
      env:
        - JOB="2.7, locale, slow, old NumPy" ENV_FILE="ci/deps/travis-27-locale.yaml" LOCALE_OVERRIDE="zh_CN.UTF-8" SLOW=true
      addons:
        apt:
          packages:
          - language-pack-zh-hans
    - dist: trusty
      env:
        - JOB="2.7" ENV_FILE="ci/deps/travis-27.yaml" TEST_ARGS="--skip-slow"
      addons:
        apt:
          packages:
          - python-gtk2
    - dist: trusty
      env:
        - JOB="3.6, coverage" ENV_FILE="ci/deps/travis-36.yaml" TEST_ARGS="--skip-slow --skip-network" PANDAS_TESTING_MODE="deprecate" COVERAGE=true
    - dist: trusty
      env:
        - JOB="3.7, NumPy dev" ENV_FILE="ci/deps/travis-37-numpydev.yaml" TEST_ARGS="--skip-slow --skip-network -W error" PANDAS_TESTING_MODE="deprecate"
      addons:
        apt:
          packages:
          - xsel

    # In allow_failures
    - dist: trusty
      env:
        - JOB="3.6, slow" ENV_FILE="ci/deps/travis-36-slow.yaml" SLOW=true

    allow_failures:
      - dist: trusty
        env:
          - JOB="3.6, slow" ENV_FILE="ci/deps/travis-36-slow.yaml" SLOW=true

before_install:
  - echo "before_install"
  # set non-blocking IO on travis
  # https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - source ci/travis_process_gbq_encryption.sh
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - pwd
  - uname -a
  - git --version
  - git tag

install:
  - echo "install start"
  - ci/prep_cython_cache.sh
  - ci/install_travis.sh
  - ci/submit_cython_cache.sh
  - echo "install done"

before_script:
  - ci/install_db_travis.sh
  # XXX checking if this is still required now that doctests are in azure
  # - export DISPLAY=":99.0"
  - ci/before_script_travis.sh

script:
  - echo "script start"
  - ci/script_single.sh
  - ci/script_multi.sh

after_success:
  -  ci/upload_coverage.sh

after_script:
  - echo "after_script start"
  - source activate pandas && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
  - if [ -e test-data-single.xml ]; then
    ci/print_skipped.py test-data-single.xml;
    fi
  - if [ -e test-data-multiple.xml ]; then
    ci/print_skipped.py test-data-multiple.xml;
    fi
  - echo "after_script done"
