language: python
python: 3.5

# To turn off cached cython files and compiler cache
# set NOCACHE-true
# To delete caches go to https://travis-ci.org/OWNER/REPOSITORY/caches or run
# travis cache --delete inside the project directory from the travis command line client
# The cache directories will be deleted if anything in ci/ changes in a commit
cache:
 ccache: true
 directories:
  - $HOME/.cache # cython cache
  - $HOME/.ccache # compiler cache

env:
  global:
    # create a github personal access token
    # cd pandas-dev/pandas
    # travis encrypt 'PANDAS_GH_TOKEN=personal_access_token' -r pandas-dev/pandas
    - secure: "EkWLZhbrp/mXJOx38CHjs7BnjXafsqHtwxPQrqWy457VDFWhIY1DMnIR/lOWG+a20Qv52sCsFtiZEmMfUjf0pLGXOqurdxbYBGJ7/ikFLk9yV2rDwiArUlVM9bWFnFxHvdz9zewBH55WurrY4ShZWyV+x2dWjjceWG5VpWeI6sA="

git:
    # for cloning
    depth: false

matrix:
    fast_finish: true
    exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5

    include:
    - dist: bionic
      # 18.04
      python: 3.8-dev
      env:
        - JOB="3.8-dev" PATTERN="(not slow and not network)"


before_install:
  - echo "before_install"
  # set non-blocking IO on travis
  # https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - source ci/travis_process_gbq_encryption.sh
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - pwd
  - uname -a
  - git --version
  - ./ci/check_git_tags.sh
  # Because travis runs on Google Cloud and has a /etc/boto.cfg,
  # it breaks moto import, see:
  # https://github.com/spulec/moto/issues/1771
  # https://github.com/boto/boto/issues/3741
  # This overrides travis and tells it to look nowhere.
  - export BOTO_CONFIG=/dev/null

install:
  - echo "install start"
  - sudo apt-get install build-essential
  - pip install --no-deps -U pip wheel setuptools
  - pip install python-dateutil pytz cython pytest pytest-xdist hypothesis
  - ci/prep_cython_cache.sh
  - git clone https://github.com/numpy/numpy
  - cd numpy
  - python setup.py build_ext --inplace
  - python setup.py install
  - cd ..
  - rm -rf numpy
  - python setup.py build_ext -inplace
  - python -m pip install --no-build-isolation -e .
  #- python setup.py install
  - python -c "import sys; print(sys.version_info)"
  - python -c "import pandas as pd"
  - python -c "import hypothesis"
  #- ci/setup_env.sh
  - ci/submit_cython_cache.sh
  - echo "install done"

#before_script:
#  # display server (for clipboard functionality) needs to be started here,
#  # does not work if done in install:setup_env.sh (GH-26103)
#  - export DISPLAY=":99.0"
#  - echo "sh -e /etc/init.d/xvfb start"
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3

script:
  - echo "script start"
  #- source activate pandas-dev
  #- ci/run_tests.sh
  - pytest pandas/tests --skip-slow

after_script:
  - echo "after_script start"
  - source activate pandas-dev && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
  - ci/print_skipped.py 
  - echo "after_script done"
