# Adapted from https://github.com/numba/numba/blob/master/azure-pipelines.yml
trigger:
- master
- 1.2.x

pr:
- master
- 1.2.x

variables:
  PYTEST_WORKERS: auto

jobs:
# Mac and Linux use the same template
- template: ci/azure/posix.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14

- template: ci/azure/posix.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

- job: Docker
  pool:
    vmImage: ubuntu-20.04
  strategy:
    matrix:
      py37_32bit:
        IMAGE: manylinux2014_i686
        PATTERN: "not slow and not network and not clipboard"

      py37_aarch64:
        IMAGE: manylinux2014_aarch64
        PATTERN: "not slow and not network and not clipboard and not arm_slow"

  steps:
    - script: ci/docker_ci.sh
      displayName: 'Run Docker Build / Tests'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Publish test results for Docker build'
