# Adapted from https://github.com/numba/numba/blob/master/azure-pipelines.yml
trigger:
- master
- 1.2.x

pr:
- master
- 1.2.x

variables:
  PYTEST_WORKERS: auto

jobs:
# Mac and Linux use the same template
- template: ci/azure/posix.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14

- template: ci/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

- job: py37_32bit
  pool:
    vmImage: ubuntu-18.04

  container: quay.io/pypa/manylinux2014_i686

  steps:
    - script: |
        /opt/python/cp37-cp37m/bin/python -m venv ~/virtualenvs/pandas-dev
        . ~/virtualenvs/pandas-dev/bin/activate
        python -m pip install --no-deps -U pip wheel setuptools
        pip install cython numpy python-dateutil pytz pytest pytest-xdist hypothesis pytest-azurepipelines
      displayName: 'Setup Environment'

    - script: |
        . ~/virtualenvs/pandas-dev/bin/activate
        python setup.py build_ext -q -j2
        python -m pip install --no-build-isolation -e .
      displayName: 'Build pandas'

    - script: |
        . ~/virtualenvs/pandas-dev/bin/activate
        pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
      displayName: 'Build Version'

    - script: |
        . ~/virtualenvs/pandas-dev/bin/activate
        pytest -m -n 2 'not slow and not network and not clipboard' pandas --junitxml=test-data.xml"
      displayName: 'Run Tests'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Publish test results for Python 3.7-32 bit full Linux'
