version: 2
jobs:
  py27_compat:
    docker:
      - image: continuumio/miniconda:latest
    environment:
      JOB: "2.7_COMPAT"
      ENV_FILE: "ci/circle-27-compat.yaml"
      LOCALE_OVERRIDE: "it_IT.UTF-8"
      MINICONDA_DIR: /home/ubuntu/miniconda3
    steps:
      - checkout
      - run:
          name: build
          command: |
            ./ci/install_circle.sh
            ./ci/show_circle.sh
      - run:
          name: install database
          command: ./ci/install_db_circle.sh
      - run:
          name: test
          command: ./ci/run_circle.sh  --skip-slow --skip-network

  py36_locale:
    docker:
      - image: continuumio/miniconda:latest
    environment:
      JOB: "3.6_LOCALE"
      ENV_FILE: "ci/circle-36-locale.yaml"
      LOCALE_OVERRIDE: "zh_CN.UTF-8"
      MINICONDA_DIR: /home/ubuntu/miniconda3
    steps:
      - checkout
      - run:
          name: build
          command: |
            ./ci/install_circle.sh
            ./ci/show_circle.sh
      - run:
          name: install database
          command: ./ci/install_db_circle.sh
      - run:
          name: test
          command: ./ci/run_circle.sh  --skip-slow --skip-network

  py35_ascii:
    docker:
      - image: continuumio/miniconda:latest
    environment:
      JOB: "3.5_ASCII"
      ENV_FILE: "ci/circle-35-ascii.yaml"
      LOCALE_OVERRIDE: "C"
      MINICONDA_DIR: /home/ubuntu/miniconda3
    steps:
      - checkout
      - run:
          name: build
          command: |
            ./ci/install_circle.sh
            ./ci/show_circle.sh
      - run:
          name: install database
          command: ./ci/install_db_circle.sh
      - run:
          name: test
          command: ./ci/run_circle.sh  --skip-slow --skip-network


workflows:
  version: 2
  build_and_test:
    jobs:
      - py27_compat
      - py36_locale
      - py35_ascii
