codecov:
  branch: master

comment:
  layout: "diff"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - "master"

coverage:
  status:
    project:
      default:
        target: '82'
    patch:
      default:
        target: '50'

github_checks:
    annotations: false