name: pandas-dev
channels: 
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # test dependencies
  - cython=0.29.32
  - pytest>=6.0
  - pytest-asyncio>=0.17

  # required dependencies
  - python-dateutil
  - numpy
  - pytz
