version: 2.1

jobs:
  test-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: ENV_FILE="ci/deps/circle-37-arm64.yaml" ci/setup_env.sh
      - run: PYTEST_WORKERS="auto" PATTERN="not slow and not network and not clipboard and not arm_slow" ci/run_tests.sh

workflows:
  build:
    jobs:
      - test-arm
