version: 2.1

jobs:
  test-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    environment:
      ENV_FILE: ci/deps/circle-38-arm64.yaml
      PYTEST_WORKERS: auto
      PATTERN: "not single_cpu and not slow and not network and not clipboard and not arm_slow and not db"
      PYTEST_TARGET: "pandas"
      PANDAS_CI: "1"
    steps:
      - checkout
      - run: .circleci/setup_env.sh
      - run: PATH=$HOME/miniconda3/envs/pandas-dev/bin:$HOME/miniconda3/condabin:$PATH ci/run_tests.sh
  build-aarch:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    environment:
      TAG = << pipeline.git.tag >>
      TRIGGER_SOURCE = << pipeline.trigger_source >>
    steps:
      - checkout
      - run:
          name: Build Aarch64 wheels (3.8)
          command: |
            pip3 install cibuildwheel==2.9.0
            cibuildwheel --output-dir wheelhouse
          environment:
            CIBW_BUILD: << parameters.CIBW_BUILD >>
      - run:
          name: Upload wheels
          command: |
            if ! [[ -z ${TAG} ]]; then
                export IS_PUSH="true"
            fi
            if [[ $TRIGGER_SOURCE == "scheduled_pipeline"]]; then
                export IS_SCHEDULE_DISPATCH="true"
            fi
            source ci/upload_wheels.sh
            set_upload_vars
            upload_wheels
      - store_artifacts:
          path: wheelhouse/
workflows:
  test:
    # Don't run trigger this one when scheduled pipeline runs
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - test-arm
  build-wheels:
    jobs:
      - build-aarch64:
          matrix:
            parameters:
              CIBW_BUILD: ["cp38-manylinux_aarch64", "cp39-manylinux_aarch64", "cp310-manylinux_aarch64", "cp311-manylinux_aarch64"]
