version: 2.1

jobs:
  test-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: ENV_FILE="ci/deps/circle-37-arm64.yaml" ci/setup_env.sh
      - run: ci/run_tests.sh

workflows:
  build:
    jobs:
      - test-arm
