parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38_macos:
        ENV_FILE: ci/deps/azure-macos-38.yaml
        CONDA_PY: "38"
        PATTERN: "not slow and not network"

  steps:
    - bash: echo '##vso[task.prependpath]$CONDA/bin'
      displayName: Add conda to PATH

    - bash: sudo chown -R $USER $CONDA
      displayName: Take ownership of conda installation

    - bash: conda update --quiet --yes conda
      displayName: Update conda

    - bash: conda env create --quiet --file $(ENV_FILE)
      displayName: Create Anaconda environment

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        conda list
        python setup.py build_ext -q -j 4
        python -m pip install -e . --no-build-isolation --no-use-pep517
      displayName: Build pandas

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        ci/run_tests.sh
      displayName: Test

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        python -c "import pandas; pandas.show_versions();"
      displayName: Build versions

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: Publish test results

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        python ci/print_skipped.py
      displayName: Print skipped tests
