parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 90
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      # py38:
      #   ENV_FILE: ci/deps/actions-38.yaml
      #   CONDA_PY: "38"

      # py39:
      #   ENV_FILE: ci/deps/actions-39.yaml
      #   CONDA_PY: "39"

      py310:
        ENV_FILE: ci/deps/actions-310.yaml
        CONDA_PY: "310"

  steps:
    - task: Cache@2
      inputs:
        key: sccache-0
        restoreKeys: |
          sccache-restore-0
        path: $(HOME)/.sccache
      displayName: Restore Sccache cache

    - script: |
        set -eux
        sccache_version=v0.2.15
        sccache_archive_name=sccache-$sccache_version-x86_64-apple-darwin
        curl -L https://github.com/mozilla/sccache/releases/download/$sccache_version/$sccache_archive_name.tar.gz \
          | tar xzf - -O $sccache_archive_name/sccache > /usr/local/bin/sccache
        chmod +x /usr/local/bin/sccache
        SCCACHE_IDLE_TIMEOUT=999999 SCCACHE_DIR=$(HOME)/.sccache sccache --start-server
        sccache -s
        sccache -z
      displayName: Setup Sccache

    - task: Cache@2
      inputs:
        key: conda-0
        restoreKeys: |
          conda-restore-0
        pattern: /usr/local/miniconda/pkgs/*.tar.bz2
      displayName: Restore Conda package cache

    - script: echo '##vso[task.prependpath]/usr/local/miniconda/condabin'
      displayName: 'Set conda path asdf'

    - script: rm /usr/local/miniconda/pkgs/cache/*.json
      displayName: 'Workaround for mamba-org/mamba#488'

    - script: |
        set -eux
        conda install -y -c conda-forge -n base 'mamba>=0.22' pip
        env | grep pkg
        # See https://github.com/mamba-org/mamba/issues/633
        mamba create -q -n pandas-dev
        # TODO: GH#44980 https://github.com/pypa/setuptools/issues/2941
        echo '  - setuptools <60' >> ${ENV_FILE}
        if [ "$(uname)" == Darwin ]; then
          # From pyarrow on MacOS
          # ImportError: 2): Library not loaded: @rpath/libssl.1.1.dylib
          # Referenced from: /Users/runner/miniconda3/envs/pandas-dev/lib/libthrift.0.13.0.dylib
          # Reason: image not found
          sed -i'' -e 's/^  - pyarrow$/  - pyarrow=6/' ${ENV_FILE}
        fi
        time mamba env update -n pandas-dev --file="${ENV_FILE}"
        set +e
        echo Have qt?
        mamba list -n pandas-dev -f qt --json
        echo Have pandas?
        mamba run --no-capture-output -n pandas-dev pip list | grep pandas
        set -e
        time DISTUTILS_C_COMPILER_LAUNCHER=sccache mamba run --no-capture-output -n pandas-dev python setup.py build_ext -q -j3
        time mamba run --no-capture-output -n pandas-dev python -m pip install --no-build-isolation -e .
        sccache -s
      displayName: 'Setup environment and build pandas'

    - script: |
        mamba run --no-capture-output -n pandas-dev ci/run_tests.sh
      displayName: 'Test'

    - script: |
        pushd /tmp
        mamba run --no-capture-output -n pandas-dev python -c "import pandas; pandas.show_versions()"
        popd
      displayName: 'Build versions'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'
