parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ if eq(parameters.name, 'macOS') }}:
        latest:
          ENV_FILE: ci/deps/latest.yml
          PATTERN: "not slow and not network"

        oldest:
          ENV_FILE: ci/deps/oldest.yml
          PATTERN: "not slow and not network"

      ${{ if eq(parameters.name, 'Linux') }}:
        latest:
          ENV_FILE: ci/deps/latest.yml
          PATTERN: "not slow and not network"
          LOCALE_OVERRIDE: "zh_CN.UTF-8"
          EXTRA_APT: "language-pack-zh-hans xsel"

        oldest:
          ENV_FILE: ci/deps/oldest.yml
          PATTERN: "not slow and not network"

        slow:
          ENV_FILE: ci/deps/latest.yml
          PATTERN: "slow"

        performance:
          ENV_FILE: ci/deps/performance.yml
          PATTERN: "not slow and not network"

        32bit:
          ENV_FILE: ci/deps/32bit.yml
          PATTERN: "not slow and not network and not clipboard"
          BITS32: "yes"

        development:
          ENV_FILE: ci/deps/unstable.yml
          PATTERN: "not slow and not network"
          TEST_ARGS: "-W error"
          PANDAS_TESTING_MODE: "deprecate"

  steps:
    - script: |
        if [ "$(uname)" == "Linux" ]; then sudo apt-get install -y libc6-dev-i386 $EXTRA_APT; fi
        echo '##vso[task.prependpath]$(HOME)/miniconda3/bin'
        echo "Creating Environment"
        ci/setup_env.sh
      displayName: 'Setup environment and build pandas'

    - script: |
        source activate pandas-dev
        ci/run_tests.sh
      displayName: 'Test'

    - script: source activate pandas-dev && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
      displayName: 'Build versions'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'

    - script: |
        source activate pandas-dev
        python ci/print_skipped.py
      displayName: 'Print skipped tests'
