parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 90
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      # py38:
      #   ENV_FILE: ci/deps/actions-38.yaml
      #   CONDA_PY: "38"

      # py39:
      #   ENV_FILE: ci/deps/actions-39.yaml
      #   CONDA_PY: "39"

      py310:
        ENV_FILE: ci/deps/actions-310.yaml
        CONDA_PY: "310"

  steps:
    - script: |
        set -eux
        ls -lh
        ls -lh $(Pipeline.Workspace)
        export CONDA_PKGS_DIRS=$(Pipeline.Workspace)/conda_pkgs
        # See https://github.com/mamba-org/mamba/issues/633
        #time conda create -y -n mamba
        time conda install -y -n base -c conda-forge 'mamba>=0.22'
      displayName: Install Mamba
      condition: ne(variables.CONDA_MAMBA_ENV_CACHE_RESTORED, 'true')

    - script: |
        conda run --no-capture-output -n base mamba info
      displayName: Mamba help
