parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:

        py36_locale_slow_old_np:
          ENV_FILE: ci/deps/azure-36-locale.yaml
          CONDA_PY: "36"
          PATTERN: "slow"
          LOCALE_OVERRIDE: "zh_CN.UTF-8"
          EXTRA_APT: "language-pack-zh-hans"

        py36_locale_slow:
          ENV_FILE: ci/deps/azure-36-locale_slow.yaml
          CONDA_PY: "36"
          PATTERN: "not slow and not network"
          LOCALE_OVERRIDE: "it_IT.UTF-8"

  steps:
    - script: |
        if [ "$(uname)" == "Linux" ]; then sudo apt-get install -y libc6-dev-i386 $EXTRA_APT; fi
        echo '##vso[task.prependpath]$(HOME)/miniconda3/bin'
        echo "Creating Environment"
        ci/setup_env.sh
      displayName: 'Setup environment and build pandas'

