parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38_macos_1:
        ENV_FILE: ci/deps/azure-macos-38.yaml
        CONDA_PY: "38"
        PATTERN: "not slow"
        PYTEST_TARGET: "pandas/tests/[a-h]*"
      py38_macos_2:
        ENV_FILE: ci/deps/azure-macos-38.yaml
        CONDA_PY: "38"
        PATTERN: "not slow"
        PYTEST_TARGET: "pandas/tests/[i-z]*"
      py39_macos_1:
        ENV_FILE: ci/deps/azure-macos-39.yaml
        CONDA_PY: "39"
        PATTERN: "not slow"
        PYTEST_TARGET: "pandas/tests/[a-h]*"
      py39_macos_2:
        ENV_FILE: ci/deps/azure-macos-39.yaml
        CONDA_PY: "39"
        PATTERN: "not slow"
        PYTEST_TARGET: "pandas/tests/[i-z]*"
      py310_macos_1:
        ENV_FILE: ci/deps/azure-macos-310.yaml
        CONDA_PY: "310"
        PATTERN: "not slow"
        PYTEST_TARGET: "pandas/tests/[a-h]*"
      py310_macos_2:
        ENV_FILE: ci/deps/azure-macos-310.yaml
        CONDA_PY: "310"
        PATTERN: "not slow"
        PYTEST_TARGET: "pandas/tests/[i-z]*"

  steps:
    - script: echo '##vso[task.prependpath]$(HOME)/miniconda3/bin'
      displayName: 'Set conda path'

    - task: Cache@2
      displayName: Use cached Anaconda environment
      inputs:
        key: 'conda | "$(Agent.OS)" | $(ENV_FILE)'
        path: $(HOME)/miniconda3/
        restoreKeys: |
          python | "$(Agent.OS)"
          python
        cacheHitVar: CONDA_CACHE_RESTORED

    - script: ci/setup_env.sh
      displayName: 'Setup environment'
      condition: eq(variables.CONDA_CACHE_RESTORED, 'false')

    - script: |
        conda update -q -y -n pandas-dev --file $ENV_FILE
      displayName: 'Update packages in pandas-dev'

    - script: |
        source activate pandas-dev
        conda list pandas
        python setup.py build_ext -q -j2
        python -m pip install --no-deps -U pip wheel setuptools
        python -m pip install --no-build-isolation -e .
        echo "conda list"
        conda list
      displayName: 'Build extensions and install pandas'

    - script: |
        source activate pandas-dev
        ci/run_tests.sh
      displayName: 'Test'

    - script: source activate pandas-dev && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
      displayName: 'Build versions'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'

    - script: |
        source activate pandas-dev
        python ci/print_skipped.py
      displayName: 'Print skipped tests'
