parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 90
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      # py38:
      #   ENV_FILE: ci/deps/actions-38.yaml
      #   CONDA_PY: "38"

      # py39:
      #   ENV_FILE: ci/deps/actions-39.yaml
      #   CONDA_PY: "39"

      py310:
        ENV_FILE: ci/deps/actions-310.yaml
        CONDA_PY: "310"

  steps:
    - task: Cache@2
      inputs:
        key: mamba-0
        restoreKeys: |
          mamba-restore-0
        path: /usr/local/miniconda/envs/mamba
        cacheHitVar: CONDA_MAMBA_ENV_CACHE_RESTORED
      displayName: Conda Mamba env cache

    - script: |
        set -eux
        ls -lh
        ls -lh $(Pipeline.Workspace)
        export CONDA_PKGS_DIRS=$(Pipeline.Workspace)/conda_pkgs
        time conda install -y -n mamba -c conda-forge 'mamba>=0.22'
      displayName: Install Mamba
      condition: ne(variables.CONDA_MAMBA_ENV_CACHE_RESTORED, 'true')

    - script: |
        conda run --no-capture-output -n mamba mamba --help
      display: Mamba help
