parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py37_np17:
        ENV_FILE: ci\\deps\\azure-windows-37.yaml
        CONDA_PY: "37"
        PATTERN: "not slow and not network"

      py38_np18:
        ENV_FILE: ci\\deps\\azure-windows-38.yaml
        CONDA_PY: "38"
        PATTERN: "not slow and not network and not high_memory"

  steps:
    - powershell: |
        Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: 'Add conda to PATH'

    - script: conda update --quiet --yes conda
      displayName: Update conda

    - script: conda env create --quiet --file $(ENV_FILE)
      displayName: 'Create anaconda environment'

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        conda list
        python setup.py build_ext -q -j 4
        python -m pip install -e . --no-build-isolation --no-use-pep517
      displayName: 'Build'

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        ci/run_tests.sh
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        python ci/print_skipped.py
      displayName: 'Print skipped tests'
