parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38_np18:
        ENV_FILE: ci/deps/azure-windows-38.yaml
        CONDA_PY: "38"
        PATTERN: "not slow and not network"
        PYTEST_WORKERS: 2  # GH-42236

      py39:
        ENV_FILE: ci/deps/azure-windows-39.yaml
        CONDA_PY: "39"
        PATTERN: "not slow and not network and not high_memory"
        PYTEST_WORKERS: 2  # GH-42236

  steps:
    - powershell: |
        Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: conda update --quiet --yes conda
      displayName: Update conda

    - script: conda env create --quiet --file $(ENV_FILE)
      displayName: Create anaconda environment

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        conda list
        python setup.py build_ext -q -j 4
        python -m pip install -e . --no-build-isolation --no-use-pep517
      displayName: Build pandas

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        ci/run_tests.sh
      displayName: Test

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        python -c "import pandas; pandas.show_versions();"
      displayName: Build versions

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: Publish test results

    - bash: |
        eval "$(conda shell.bash hook)"
        conda activate pandas-dev
        python ci/print_skipped.py
      displayName: Print skipped tests
