parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38_np18_1:
        ENV_FILE: ci/deps/azure-windows-38.yaml
        CONDA_PY: "38"
        PATTERN: "not slow and not network"
        PYTEST_WORKERS: 2  # GH-42236
        PYTEST_TARGET: "pandas/tests/[a-h]*"

      py38_np18_2:
        ENV_FILE: ci/deps/azure-windows-38.yaml
        CONDA_PY: "38"
        PATTERN: "not slow and not network"
        PYTEST_WORKERS: 2  # GH-42236
        PYTEST_TARGET: "pandas/tests/[i-z]*"

      py39_1:
        ENV_FILE: ci/deps/azure-windows-39.yaml
        CONDA_PY: "39"
        PATTERN: "not slow and not network and not high_memory"
        PYTEST_WORKERS: 2  # GH-42236
        PYTEST_TARGET: "pandas/tests/[a-h]*"

      py39_2:
        ENV_FILE: ci/deps/azure-windows-39.yaml
        CONDA_PY: "39"
        PATTERN: "not slow and not network and not high_memory"
        PYTEST_WORKERS: 2  # GH-42236
        PYTEST_TARGET: "pandas/tests/[i-z]*"

  steps:
    - powershell: |
        Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        Write-Host "##vso[task.prependpath]$HOME/miniconda3/bin"
      displayName: 'Add conda to PATH'

    - script: conda update -q -n base conda
      displayName: 'Update conda'

    - script: conda info
      displayName: 'Display conda info'

    - task: Cache@2
      displayName: Use cached Anaconda environment
      inputs:
        key: 'conda | "$(Agent.OS)" | $(ENV_FILE)'
        path: C:\Miniconda
        restoreKeys: |
          python | "$(Agent.OS)"
          python
        cacheHitVar: CONDA_CACHE_RESTORED

    - bash: |
        conda env create -q --file ci\\deps\\azure-windows-$(CONDA_PY).yaml
      displayName: 'Create anaconda environment'
      condition: eq(variables.CONDA_CACHE_RESTORED, 'false')

    - bash: |
        source activate pandas-dev
        conda list
        python setup.py build_ext -q -j 4
        python -m pip install --no-build-isolation -e .
      displayName: 'Build and install pandas'

    - bash: |
        source activate pandas-dev
        wmic.exe cpu get caption, deviceid, name, numberofcores, maxclockspeed
        ci/run_tests.sh
      displayName: 'Test'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'

    - bash: |
        source activate pandas-dev
        python ci/print_skipped.py
      displayName: 'Print skipped tests'
