name: Setup Python and install requirements
inputs:
  python-version:
    required: true
  architecture:
    default: x64
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.architecture }}

    - name: Fix $PATH on macOS
      run: |
        # On macOS, the Python version we installed above is too late in $PATH
        # to be effective if using "bash -l" (which we need for code that works
        # with Conda envs).
        cat >> ~/.bash_profile <<EOF
          export PATH="\$(echo "\$PATH" | grep -Eio '[^:]+hostedtoolcache/python[^:]+bin'):\$PATH" \
        EOF
      shell: bash -el {0}
      if: ${{ runner.os == 'macOS' }}

    - name: Install dependencies
      run: |
        pip install -r ci/deps/pip-requirements.txt
        pip list
      shell: bash -el {0}
