name: Build pandas
description: Rebuilds the C extensions and installs pandas
inputs:
  editable:
    description: Whether to build pandas in editable mode (default true)
    default: true
  sanitize:
    description: Whether sanitizers should be used or not
    default: false
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
        pip list --pre
      shell: bash -el {0}

    - name: Uninstall existing Pandas installation
      run: |
        if pip show pandas 1>/dev/null; then
          pip uninstall -y pandas
        fi
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        if [[ ${{ inputs.editable }} == "true" ]]; then
          if [[ ${{ inputs.sanitize }} == "true" ]]; then
            pip install -e . --no-build-isolation -v  --config-settings=setup-args="-Db_sanitize=address,undefined"
          else
            pip install -e . --no-build-isolation -v
          fi
        else
          if [[ ${{ inputs.sanitize }} == "true" ]]; then
            pip install . --no-build-isolation -v --config-settings=setup-args="-Db_sanitize=address,undefined"
          else
            pip install . --no-build-isolation -v
          fi
        fi
      shell: bash -el {0}
