name: pandas-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - Cython
  - ipython
  - matplotlib
  - NumPy
  - moto
  - nbsphinx
  - pytest>=3.1
  - python-dateutil>=2.5.0
  - python=3
  - pytz
  - setuptools>=3.3
  - sphinx
