name: Run tests and report results
inputs:
  sanitize:
    description: Whether sanitizers should be used or not
    default: false
runs:
  using: composite
  steps:
    - name: Test
      run: |
        if [[ ${{ inputs.sanitize }} == "true" ]]; then
          ASAN_OPTIONS=detect_leaks=0 \
            LD_PRELOAD=$(gcc -print-file-name=libasan.so) \
            ci/run_tests.sh
        else
          ci/run_tests.sh
        fi
      shell: bash -el {0}

    - name: Publish test results
      uses: actions/upload-artifact@v3
      with:
        name: Test results
        path: test-data.xml
      if: failure()

    - name: Report Coverage
      run: coverage report -m
      shell: bash -el {0}
      if: failure()

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        name: codecov-pandas
        fail_ci_if_error: false
      if: failure()
