name: Linkcheck
on:
    workflow_dispatch: # Enable manual triggering
    #schedule:
    # Run monthly on the 1st day of the month
        #- cron: '0 0 1 * *'
    pull_request:
      paths:
        - ".github/workflows/broken-linkcheck.yml"
        - "doc/make.py"
jobs:
    linkcheck:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
                fetch-depth: 0
               
        - name: Set up Conda
          uses: ./.github/actions/setup-conda

        - name: Build Pandas
          uses: ./.github/actions/build_pandas

        - name: Setup Python
          id: setup_python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            cache: 'pip'
            cache-dependency-path: 'requirements-dev.txt'

        - name: Install requirements-dev.txt
          run: pip install -r requirements-dev.txt

        - name: Run linkcheck script
          working-directory: ./doc
          run: python make.py linkcheck
