name: Create Issue
on:
  schedule:
  # Run monthly on the 1st day of the month
    - cron: '0 0 1 * *'
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Conda
        uses: ./.github/actions/setup-conda

      - name: Build Pandas
        uses: ./.github/actions/build_pandas
      - name: Run create-issue script
        working-directory: ./doc        
