name: Database

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - 1.2.x

env:
  PYTEST_WORKERS: "auto"

jobs:
  Linux_py37_locale:
    name: Linux_py37_locale
    runs-on: ubuntu-latest

    env:
      CONDA_PY: "37"
      ENV_FILE: ci/deps/actions-37-locale.yaml
      PATTERN: ((not slow and not network and not clipboard) or (single and db))
      LOCALE_OVERRIDE: zh_CN.UTF-8

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pandas

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

    - name: Setting conda path
      run: echo "${HOME}/miniconda3/bin" >> $GITHUB_PATH

    - name: Checkout
      uses: actions/checkout@v2

    # - name: Initialize Database
    #   run:
    #       # mysql -e 'create database pandas_nosetest;'
    #       psql -c 'create database pandas_nosetest;' -U postgres
    #   env:
    #       POSTGRES_HOST: localhost
    #       POSTGRES_PORT: 5432

    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if the environment file has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('ci/deps/actions-37-locale.yaml') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pandas-dev
        channel-priority: strict
        environment-file: ${{ env.ENV_FILE }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Build Pandas
      run: |
        python setup.py build_ext -j 2
        python -m pip install -e . --no-build-isolation --no-use-pep517

    - name: Test
      run: |
        ci/run_tests.sh
      if: always()

    - name: Publish test results
      uses: actions/upload-artifact@master
      with:
        name: Test results
        path: test-data.xml
      if: failure()

    - name: Print skipped tests
      run: python ci/print_skipped.py
