name: Database

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - 1.1.x

env:
  PYTEST_WORKERS: "auto"
  SQL: 1

jobs:
  Linux_py38_slow:
    name: Linux_py38_slow
    runs-on: ubuntu-latest

    env:
      CONDA_PY: "38"
      ENV_FILE: ci/deps/actions-38-slow.yaml
      PATTERN: slow

    defaults:
      run:
        shell: bash -l {0}

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pandas_nosetest

        ports:
        - 5432/tcp

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Setting conda path
      run: echo "${HOME}/miniconda3/bin" >> $GITHUB_PATH

    - name: Checkout
      uses: actions/checkout@v2

    # - name: Start MySQL
    #   run:
    #     sudo systemctl enable mysql.service
    #     sudo systemctl start mysql.service

    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if the environment file has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('ci/deps/actions-38-slow.yaml') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pandas-dev
        channel-priority: strict
        environment-file: ${{ env.ENV_FILE }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Build Pandas
      run: |
        python setup.py build_ext -j 2
        python -m pip install -e . --no-build-isolation --no-use-pep517

    - name: Test
      run: ci/run_tests.sh
      if: always()

    - name: Publish test results
      uses: actions/upload-artifact@master
      with:
        name: Test results
        path: test-data.xml
      if: failure()
