name: Posix

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - 1.2.x

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        env-file: [
          [ci/deps/azure-37-minimum_versions.yaml, "not slow and not network and not clipboard", ""],
          [ci/deps/azure-37.yaml, "not slow and not network and not clipboard", ""],
          [ci/deps/azure-37-locale_slow.yaml, "slow", "language-pack-it xsel"]
        ]
      fail-fast: true
    env:
      COVERAGE: true
      PYTEST_WORKERS: "auto"
      ENV_FILE: ${{ matrix.env-file[0] }}
      PATTERN: ${{ matrix.env-file[1] }}
      EXTRA_APT: ${{ matrix.env-file[2] }}


    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache conda
      uses: actions/cache@v1
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('${{ env.ENV_FILE }}') }}

    - name: Extra installs
      run: sudo apt-get update && sudo apt-get install -y libc6-dev-i386 ${{ env.EXTRA_APT }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pandas-dev
        channel-priority: flexible
        environment-file: ${{ env.ENV_FILE }}
        use-only-tar-bz2: true

    - name: Build Pandas
      uses: ./.github/actions/build_pandas

    - name: Test
      run: ci/run_tests.sh
      if: always()

    - name: Build Version
      run: pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd

    - name: Publish test results
      uses: actions/upload-artifact@master
      with:
        name: Test results
        path: test-data.xml
      if: failure()

    - name: Print skipped tests
      run: python ci/print_skipped.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: /tmp/test_coverage.xml
        flags: unittests
        name: codecov-pandas
        fail_ci_if_error: true
