name: pre-commit

on:
  pull_request:
    paths-ignore:
      - "doc/**"
  push:
    branches: [master]
    paths-ignore:
      - "doc/**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
