name: pre-commit

on:
  pull_request:
    paths-ignore:
      - "doc/**"
  push:
    branches: [master]
    # NOTE: Is this really needed?
    # The pre-commit also checks "rst" files,
    # and also the checks are very fast.
    paths-ignore:
      - "doc/**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
