name: Python Dev

on:
  push:
    branches:
      - main
      - 1.4.x
  pull_request:
    branches:
      - main
      - 1.4.x
    paths-ignore:
      - "doc/**"

env:
  PYTEST_WORKERS: "auto"
  PANDAS_CI: 1
  PATTERN: "not slow and not network and not clipboard and not single_cpu"
  COVERAGE: true
  PYTEST_TARGET: pandas

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: actions-311-dev
    timeout-minutes: 80

    concurrency:
      #https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.os }}-${{ matrix.pytest_target }}-dev
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python Dev Version
      uses: actions/setup-python@v4
      with:
        python-version: '3.11-dev'

    - name: Install dependencies
      shell: bash -el {0}
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install git+https://github.com/cython/cython.git
        python3 -m pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy
        python3 -m pip install git+https://github.com/nedbat/coveragepy.git
        python3 -m pip install python-dateutil pytz hypothesis pytest>=6.2.5 pytest-xdist pytest-cov pytest-asyncio>=0.17
        python3 -m pip list

    - name: Build Pandas
      run: |
        python3 setup.py build_ext -q -j2
        python3 -m pip install -e . --no-build-isolation --no-use-pep517

    - name: Build Version
      run: |
        python3 -c "import pandas; pandas.show_versions();"

    - name: Test
      uses: ./.github/actions/run-tests
