# This file is purposely frozen(does not run). DO NOT DELETE IT
# Unfreeze(by commentingthe if: false() condition) once the
# next Python Dev version has released beta 1 and both Cython and numpy support it
# After that Python has released, migrate the workflows to the
# posix GHA workflows/Azure pipelines and "freeze" this file by
# uncommenting the if: false() condition
# Feel free to modify this comment as necessary.

name: Python Dev

on:
  push:
    branches:
      - main
      - 1.4.x
  pull_request:
    branches:
      - main
      - 1.4.x
    paths-ignore:
      - "doc/**"

env:
  PANDAS_CI: 1
  PYTEST_TARGET: pandas
  PYTEST_WORKERS: "auto"
  PATTERN: "not slow and not network and not clipboard and not single_cpu"
  COVERAGE: true

jobs:
  build:
    if: false # Comment this line out to "unfreeze"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.11-dev"]

    name: ${{ matrix.python-version }}
    timeout-minutes: 80
    defaults:
      run:
        shell: bash -el {0}

    concurrency:
      #https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.os }}-dev
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }} and install dependencies
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install NumPy nightly
      run:
        pip install -Ui https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy

    - name: Build pandas
      uses: ./.github/actions/build-pandas

    - name: Install pandas from sdist
      run: |
        # Double check that we have the expected Python and NumPy
        python --version
        pip list
        python --version | grep -i "$(echo "${{ matrix.python-version }}" | sed 's/-.*//')"
        pip list | egrep -i "numpy.+dev"

    - name: Run tests
      uses: ./.github/actions/run-tests
