name: sdist

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 1.2.x

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install numpy cython python-dateutil pytz hypothesis pytest pytest-xdist
        pip list

    - name: Build Pandas sdist
      run: |
        python setup.py sdist --formats=gztar

    - name: Install Pandas From sdist
      run: |
        pip install dist/*.gz

    - name: Build Version
      run: |
        python -c "import pandas; pandas.show_versions();"

    - name: Test with pytest
      run: |
        python -c "import pandas; pandas.test(extra_args=['-m not clipboard', '--skip-slow', '--skip-network', '--skip-db', '-n=2'])"
      continue-on-error: true

    - name: Publish test results
      uses: actions/upload-artifact@master
      with:
        name: Test results
        path: test-data.xml
      if: failure()
