name: sdist

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 1.2.x
      - 1.3.x
    paths-ignore:
      - "doc/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: sdist test
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install numpy

    - name: Build Pandas sdist
      run: |
        pip list
        python setup.py sdist --formats=gztar

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pandas-sdist
        python-version: ${{ matrix.python-version }}

    - name: Install Pandas From sdist
      run: |
        conda install cython
        python -m pip install dist/*.gz

    - name: Build Version
      run: |
        cd ..
        python -c "import pandas; pandas.show_versions();"
