name: Web and docs

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup environment and build pandas
      run: |
        sudo apt-get install -y libc6-dev-i386
        ci/setup_env.sh

    - name: Build website
      run: |
        source activate pandas-dev
        python web/pandas_web.py web/pandas --target-path=web/build

    - name: Build documentation
      run: |
        source activate pandas-dev
        # Next we should simply have `doc/make.py --warnings-are-errors`,
        # everything else is required because the ipython directive doesn't fail the build on errors
        # (https://github.com/ipython/ipython/issues/11547)
        doc/make.py --warnings-are-errors | tee sphinx.log ; SPHINX_RET=${PIPESTATUS[0]}
        grep -B1 "^<<<-------------------------------------------------------------------------$" sphinx.log ; IPY_RET=$(( $? != 1 ))
        exit $(( $SPHINX_RET + $IPY_RET ))

    - name: Merge website and docs
      run: |
        mkdir -p to_deploy/docs
        cp -r web/build/* to_deploy/
        cp -r doc/build/html/* to_deploy/docs/
