name: pandas

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  ENV_FILE: environment.yml
  # TODO: remove export PATH=... in each step once this works
  # PATH: $HOME/miniconda3/bin:$PATH

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Looking for unwanted patterns
      run: ci/code_checks.sh patterns
      if: true

    - name: Setup environment and build pandas
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        ci/setup_env.sh
      if: true

    - name: Linting
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        ci/code_checks.sh lint
      if: true

    - name: Dependencies consistency
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        ci/code_checks.sh dependencies
      if: true

    - name: Checks on imported code
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        ci/code_checks.sh code
      if: true

    - name: Running doctests
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        ci/code_checks.sh doctests
      if: true

    - name: Docstring validation
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        ci/code_checks.sh docstrings
      if: true

    - name: Typing validation
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        ci/code_checks.sh docstrings
      if: true

    - name: Testing docstring validation script
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        pytest --capture=no --strict scripts
      if: true

    - name: Running benchmarks
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        cd asv_bench
        asv check -E existing
        git remote add upstream https://github.com/pandas-dev/pandas.git
        git fetch upstream
        if git diff upstream/master --name-only | grep -q "^asv_bench/"; then
            asv machine --yes
            ASV_OUTPUT="$(asv dev)"
            if [[ $(echo "$ASV_OUTPUT" | grep "failed") ]]; then
                echo "##vso[task.logissue type=error]Benchmarks run with errors"
                echo "$ASV_OUTPUT"
                exit 1
            else
                echo "Benchmarks run without errors"
            fi
        else
            echo "Benchmarks did not run, no changes detected"
        fi
      if: true

  web_and_docs:
    name: Web and docs
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    # actions/checkout doesn't fetch all tags, and that breaks pandas.__version__
    - name: Fetch tags
      run: |
        set -v
        git tag
        git fetch --tags
        git tag
        set +v

    - name: Setup environment and build pandas
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        ci/setup_env.sh

    - name: Build website
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        python web/pandas_web.py web/pandas --target-path=web/build

    - name: Build documentation
      run: |
        export PATH=$HOME/miniconda3/bin:$PATH
        source activate pandas-dev
        # Next we should simply have `doc/make.py --warnings-are-errors`,
        # everything else is required because the ipython directive doesn't fail the build on errors
        # (https://github.com/ipython/ipython/issues/11547)
        doc/make.py --warnings-are-errors | tee sphinx.log ; SPHINX_RET=${PIPESTATUS[0]}
        grep -B1 "^<<<-------------------------------------------------------------------------$" sphinx.log ; IPY_RET=$(( $? != 1 ))
        exit $(( $SPHINX_RET + $IPY_RET ))

    - name: Merge website and docs
      run: |
        mkdir -p pandas_web/docs
        cp -r web/build/* pandas_web/
        cp -r doc/build/html/* pandas_web/docs/

    - name: Create artifact
      run: |
        tar -czvf pandas_web.tar.gz pandas_web

    - name: Upload artifact
      uses: actions/upload-artifact@master
